# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainUi(object):
    def setupUi(self, mainUi):
        mainUi.setObjectName("mainUi")
        mainUi.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(mainUi)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(mainUi)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loginPage)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.loginPage)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.loginPage)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.groupBox = QtWidgets.QGroupBox(self.loginPage)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.faUsername = QtWidgets.QLineEdit(self.groupBox)
        self.faUsername.setObjectName("faUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.faUsername)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.faPassword = QtWidgets.QLineEdit(self.groupBox)
        self.faPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.faPassword.setObjectName("faPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.faPassword)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setMinimumSize(QtCore.QSize(120, 60))
        self.graphicsView.setMaximumSize(QtCore.QSize(120, 60))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.faCaptcha = QtWidgets.QLineEdit(self.groupBox)
        self.faCaptcha.setObjectName("faCaptcha")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.faCaptcha)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.loginPage)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.wzlApiKey = QtWidgets.QLineEdit(self.groupBox_2)
        self.wzlApiKey.setObjectName("wzlApiKey")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.wzlApiKey)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.loginPage)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.stackedWidget.addWidget(self.loginPage)
        self.folderPage = QtWidgets.QWidget()
        self.folderPage.setObjectName("folderPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.folderPage)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.folderPage)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.folderPage)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.folderPage)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.faFolders = QtWidgets.QTreeWidget(self.groupBox_3)
        self.faFolders.setObjectName("faFolders")
        self.faFolders.headerItem().setText(0, "1")
        self.verticalLayout_4.addWidget(self.faFolders)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.folderPage)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wzlFolders = QtWidgets.QTreeWidget(self.groupBox_4)
        self.wzlFolders.setObjectName("wzlFolders")
        self.wzlFolders.headerItem().setText(0, "1")
        self.verticalLayout_5.addWidget(self.wzlFolders)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.folderPage)
        self.groupBox_5.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.folderTitle = QtWidgets.QLabel(self.groupBox_5)
        self.folderTitle.setText("")
        self.folderTitle.setObjectName("folderTitle")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.folderTitle)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnResetFolders = QtWidgets.QPushButton(self.folderPage)
        self.btnResetFolders.setObjectName("btnResetFolders")
        self.horizontalLayout_4.addWidget(self.btnResetFolders)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btnCreateFolders = QtWidgets.QPushButton(self.folderPage)
        self.btnCreateFolders.setObjectName("btnCreateFolders")
        self.horizontalLayout_4.addWidget(self.btnCreateFolders)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.stackedWidget.addWidget(self.folderPage)
        self.submissionPage = QtWidgets.QWidget()
        self.submissionPage.setObjectName("submissionPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.submissionPage)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.submissionPage)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.submissionPage)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_6 = QtWidgets.QGroupBox(self.submissionPage)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.faSubmissions = QtWidgets.QTreeWidget(self.groupBox_6)
        self.faSubmissions.setObjectName("faSubmissions")
        self.faSubmissions.headerItem().setText(0, "1")
        self.verticalLayout_7.addWidget(self.faSubmissions)
        self.horizontalLayout_5.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.submissionPage)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.wzlSubmissions = QtWidgets.QTreeWidget(self.groupBox_7)
        self.wzlSubmissions.setObjectName("wzlSubmissions")
        self.wzlSubmissions.headerItem().setText(0, "1")
        self.verticalLayout_8.addWidget(self.wzlSubmissions)
        self.horizontalLayout_5.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.submissionPage)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.submissionThumbnail = QtWidgets.QGraphicsView(self.groupBox_8)
        self.submissionThumbnail.setMaximumSize(QtCore.QSize(200, 200))
        self.submissionThumbnail.setObjectName("submissionThumbnail")
        self.verticalLayout_6.addWidget(self.submissionThumbnail)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_5.addWidget(self.groupBox_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.groupBox_9 = QtWidgets.QGroupBox(self.submissionPage)
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_9)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout_9.addWidget(self.groupBox_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnResetSubmissions = QtWidgets.QPushButton(self.submissionPage)
        self.btnResetSubmissions.setObjectName("btnResetSubmissions")
        self.horizontalLayout_6.addWidget(self.btnResetSubmissions)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.btnCreateSubmissions = QtWidgets.QPushButton(self.submissionPage)
        self.btnCreateSubmissions.setObjectName("btnCreateSubmissions")
        self.horizontalLayout_6.addWidget(self.btnCreateSubmissions)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.submissionPage)
        self.progressPage = QtWidgets.QWidget()
        self.progressPage.setObjectName("progressPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.progressPage)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_13 = QtWidgets.QLabel(self.progressPage)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.overallProgress = QtWidgets.QProgressBar(self.progressPage)
        self.overallProgress.setProperty("value", 24)
        self.overallProgress.setObjectName("overallProgress")
        self.verticalLayout_10.addWidget(self.overallProgress)
        self.waitProgress = QtWidgets.QProgressBar(self.progressPage)
        self.waitProgress.setProperty("value", 24)
        self.waitProgress.setTextVisible(False)
        self.waitProgress.setObjectName("waitProgress")
        self.verticalLayout_10.addWidget(self.waitProgress)
        self.log = QtWidgets.QTextEdit(self.progressPage)
        self.log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout_10.addWidget(self.log)
        self.stackedWidget.addWidget(self.progressPage)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(mainUi)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(mainUi)

    def retranslateUi(self, mainUi):
        _translate = QtCore.QCoreApplication.translate
        mainUi.setWindowTitle(_translate("mainUi", "Form"))
        self.label.setText(_translate("mainUi", "<html><head/><body><p><span style=\" font-size:20pt;\">Authenticate</span></p></body></html>"))
        self.label_2.setText(_translate("mainUi", "<html><head/><body><p>Enter your FurAffinity credentials, and a Weasyl API key.</p></body></html>"))
        self.groupBox.setTitle(_translate("mainUi", "FurAffinity Login"))
        self.label_3.setText(_translate("mainUi", "Username:"))
        self.label_4.setText(_translate("mainUi", "Password:"))
        self.label_5.setText(_translate("mainUi", "CAPTCHA:"))
        self.groupBox_2.setTitle(_translate("mainUi", "Weasyl Login"))
        self.label_6.setText(_translate("mainUi", "API Key:"))
        self.pushButton.setText(_translate("mainUi", "Log In"))
        self.label_7.setText(_translate("mainUi", "<html><head/><body><p><span style=\" font-size:20pt;\">Folders</span></p></body></html>"))
        self.label_8.setText(_translate("mainUi", "<html><head/><body><p>Copy your gallery folder structure from FurAffinity to Weasyl. The tree on the right shows the final structure. Items in green will be created. You may drag a new folder onto an existing folder to merge them together.</p></body></html>"))
        self.groupBox_3.setTitle(_translate("mainUi", "FurAffinity Folders"))
        self.groupBox_4.setTitle(_translate("mainUi", "Weasyl Folders"))
        self.groupBox_5.setTitle(_translate("mainUi", "Folder Info"))
        self.label_9.setText(_translate("mainUi", "Title:"))
        self.btnResetFolders.setText(_translate("mainUi", "Reset"))
        self.btnCreateFolders.setText(_translate("mainUi", "Create Folders"))
        self.label_10.setText(_translate("mainUi", "<html><head/><body><p><span style=\" font-size:20pt;\">Submissions</span></p></body></html>"))
        self.label_11.setText(_translate("mainUi", "<html><head/><body><p>Copy submissions from FurAffinity to Weasyl. The final result will be displayed on the right. Items in green will be created. You may drag new submissions into different folders to change their destination. Weasyl only supports sorting submissions into at most one folder.</p></body></html>"))
        self.groupBox_6.setTitle(_translate("mainUi", "FurAffinity Submissions"))
        self.groupBox_7.setTitle(_translate("mainUi", "Weasyl Submissions"))
        self.groupBox_8.setTitle(_translate("mainUi", "Submission Info"))
        self.groupBox_9.setTitle(_translate("mainUi", "Upload Settings"))
        self.label_12.setText(_translate("mainUi", "Minutes To Wait Between Uploads:"))
        self.btnResetSubmissions.setText(_translate("mainUi", "Reset"))
        self.btnCreateSubmissions.setText(_translate("mainUi", "Upload"))
        self.label_13.setText(_translate("mainUi", "<html><head/><body><p><span style=\" font-size:20pt;\">Copying Gallery</span></p></body></html>"))

